############################################################################
# apps/system/piousbhost/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME = $(CONFIG_SYSTEM_PIOUSBHOST_PROGNAME)
PRIORITY = $(CONFIG_SYSTEM_PIOUSBHOST_PRIORITY)
STACKSIZE = $(CONFIG_SYSTEM_PIOUSBHOST_STACKSIZE)
MODULE = $(CONFIG_SYSTEM_PIOUSBHOST)

MAINSRC = piousbhost_main.c

include $(APPDIR)/Application.mk
