############################################################################
# apps/system/bootguard/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME = $(CONFIG_SYSTEM_BOOTGUARD_PROGNAME)
PRIORITY = $(CONFIG_SYSTEM_BOOTGUARD_PRIORITY)
STACKSIZE = $(CONFIG_SYSTEM_BOOTGUARD_STACKSIZE)
MODULE = $(CONFIG_SYSTEM_BOOTGUARD)

MAINSRC = bootguard_main.c

include $(APPDIR)/Application.mk
