############################################################################
# apps/system/sdmount/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_SYSTEM_SDMOUNT_PROGNAME)
PRIORITY  = $(CONFIG_SYSTEM_SDMOUNT_PRIORITY)
STACKSIZE = $(CONFIG_SYSTEM_SDMOUNT_STACKSIZE)
MODULE    = $(CONFIG_SYSTEM_SDMOUNT)

MAINSRC = sdmount_main.c

include $(APPDIR)/Application.mk
