############################################################################
# apps/system/dvictrl/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_SYSTEM_DVICTRL_PROGNAME)
PRIORITY  = $(CONFIG_SYSTEM_DVICTRL_PRIORITY)
STACKSIZE = $(CONFIG_SYSTEM_DVICTRL_STACKSIZE)
MODULE    = $(CONFIG_SYSTEM_DVICTRL)

MAINSRC = dvictrl_main.c

include $(APPDIR)/Application.mk
